import styled, { keyframes } from 'styled-components'
import constants from '../constants';

export default function Loading({ size = 32 }) {

  return (
    <Container>
      <Spinner size={size}>
        <div></div>
      </Spinner>
    </Container>
  );
}

// CSS generated by https://loading.io/ and adapted to styled-components

const rotate = keyframes`
  0% { transform: translate(-50%,-50%) rotate(0deg); }
  100% { transform: translate(-50%,-50%) rotate(360deg); }
`;

const Container = styled.div`
  width: 100%;
  height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
  background: none;
`;

const Spinner = styled.div`
  background-color: red;

  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0;

  & div {
    position: absolute;
    width: ${props => props.size}px;
    height: ${props => props.size}px;
    border: ${props => props.size * 0.15}px solid ${constants.colors.primary};
    border-top-color: transparent;
    border-radius: 50%;
  }
  
  & div {
    animation: ${rotate} 1s linear infinite;
  }

  & div {
    box-sizing: content-box;
  }

`;
